name: matrix_rest_api
description: Client for matrix.org REST api, used by Sputnik Messenger
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  json_annotation: ^2.4.0
  chopper: ^2.4.2



dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  chopper_generator: ^2.0.0
  test: ^1.6.5


