import 'package:matrix_rest_api/src/api/common/converter/json_factory.dart';
import 'package:matrix_rest_api/src/api/common/converter/json_serializable_converter.dart';
import 'package:matrix_rest_api/src/api/matrix_client_api/r0/model/model.dart';

final _factories = <Type, JsonFactory>{
  MatrixUserIdentifier: (json) => MatrixUserIdentifier.fromJson(json),
  ThirdPartyUserIdentifier: (json) => ThirdPartyUserIdentifier.fromJson(json),
  PhoneUserIdentifier: (json) => PhoneUserIdentifier.fromJson(json),
  PasswordLoginRequest: (json) => PasswordLoginRequest.fromJson(json),
  TokenLoginRequest: (json) => TokenLoginRequest.fromJson(json),
  LoginResponse: (json) => LoginResponse.fromJson(json),
  SupportedVersions: (json) => SupportedVersions.fromJson(json),
  LoginResponse: (json) => LoginResponse.fromJson(json),
  Event: (json) => Event.fromJson(json),
  RoomEvent: (json) => RoomEvent.fromJson(json),
  PutEventResponse: (json) => PutEventResponse.fromJson(json),
  NameContent: (json) => NameContent.fromJson(json),
  TopicContent: (json) => TopicContent.fromJson(json),
  AliasesContent: (json) => AliasesContent.fromJson(json),
  AvatarContent: (json) => AvatarContent.fromJson(json),
  Notifications: (json) => Notifications.fromJson(json),
  PowerLevels: (json) => PowerLevels.fromJson(json),
  CreateContent: (json) => CreateContent.fromJson(json),
  PreviousRoom: (json) => PreviousRoom.fromJson(json),
  MemberContent: (json) => MemberContent.fromJson(json),
  Signed: (json) => Signed.fromJson(json),
  Invite: (json) => Invite.fromJson(json),
  JoinRuleContent: (json) => JoinRuleContent.fromJson(json),
  TombstoneContent: (json) => TombstoneContent.fromJson(json),
  NoticeMessage: (json) => NoticeMessage.fromJson(json),
  AudioInfo: (json) => AudioInfo.fromJson(json),
  AudioMessage: (json) => AudioMessage.fromJson(json),
  GenericMessage: (json) => GenericMessage.fromJson(json),
  TextMessage: (json) => TextMessage.fromJson(json),
  EmoteMessage: (json) => EmoteMessage.fromJson(json),
  ImageInfo: (json) => ImageInfo.fromJson(json),
  ThumbnailInfo: (json) => ThumbnailInfo.fromJson(json),
  ImageMessage: (json) => ImageMessage.fromJson(json),
  EncryptionContent: (json) => EncryptionContent.fromJson(json),
  CanonicalAliasContent: (json) => CanonicalAliasContent.fromJson(json),
  ContentUriResponse: (json) => ContentUriResponse.fromJson(json),
  RoomMessagesResponse: (json) => RoomMessagesResponse.fromJson(json),
  SyncResponse: (json) => SyncResponse.fromJson(json),
  JoinedRoom: (json) => JoinedRoom.fromJson(json),
  InviteState: (json) => InviteState.fromJson(json),
  Rooms: (json) => Rooms.fromJson(json),
  Presence: (json) => Presence.fromJson(json),
  InvitedRoom: (json) => InvitedRoom.fromJson(json),
  UnreadNotificationCounts: (json) => UnreadNotificationCounts.fromJson(json),
  Ephemeral: (json) => Ephemeral.fromJson(json),
  LeftRoom: (json) => LeftRoom.fromJson(json),
  DeviceList: (json) => DeviceList.fromJson(json),
  StrippedState: (json) => StrippedState.fromJson(json),
  RoomSummary: (json) => RoomSummary.fromJson(json),
  Timeline: (json) => Timeline.fromJson(json),
  AccountData: (json) => AccountData.fromJson(json),
  ToDevice: (json) => ToDevice.fromJson(json),
  State: (json) => State.fromJson(json),
  BaseUrl: (json) => BaseUrl.fromJson(json),
  WellKnownClient: (json) => WellKnownClient.fromJson(json),
  SupportedLoginFlows: (json) => SupportedLoginFlows.fromJson(json),
};

class MatrixClientApiModelConverter extends JsonSerializableConverter {
  MatrixClientApiModelConverter() : super(_factories);
}
